using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StartScene : MonoBehaviour {

    public Building building;
    public bool startscene;
    ResourceManager resources;

    public BuildingTypes house;
    public BuildingTypes[] commercial;
    public BuildingTypes road;
    public BuildingTypes townHall;
    public BuildingTypes hospital;
    public BuildingTypes police;
    public BuildingTypes fireStation;
    
    void Start ()
    {
        resources = transform.GetComponent<ResourceManager>();
        //0 = nothing
        //1 = road
        //2 = house
        //3 = store
        //4 = town hall
        //5 = office
        //6 = hospital
        //7 = police station
        //8 = fire station

        if (startscene)
        {
            resources.creative = true;
            TextFileTest();   //UNCOMMENT THIS FOR START SCENE

            building.obj = 0;
            building.ResetObjectToBuild(null);

            resources.creative = false;
        }
    }

    void TextFileTest ()
    {
        building.ResetObjectToBuild(townHall);
        building.PlaceBuilding(new Cells(255, 258), Direction.North);
        building.ResetObjectToBuild(hospital);
        building.PlaceBuilding(new Cells(270, 248), Direction.East);
        building.ResetObjectToBuild(house);
        building.PlaceBuilding(new Cells(253, 258), Direction.North);
        building.PlaceBuilding(new Cells(251, 258), Direction.North);
        building.PlaceBuilding(new Cells(249, 258), Direction.North);
        building.PlaceBuilding(new Cells(247, 258), Direction.North);
        building.PlaceBuilding(new Cells(245, 258), Direction.North);
        building.PlaceBuilding(new Cells(250, 255), Direction.South);
        building.PlaceBuilding(new Cells(248, 255), Direction.South);
        building.PlaceBuilding(new Cells(246, 255), Direction.South);
        building.PlaceBuilding(new Cells(260, 253), Direction.North);
        building.PlaceBuilding(new Cells(258, 253), Direction.North);
        building.PlaceBuilding(new Cells(256, 253), Direction.North);
        building.PlaceBuilding(new Cells(254, 253), Direction.North);
        building.PlaceBuilding(new Cells(252, 253), Direction.North);
        building.PlaceBuilding(new Cells(250, 253), Direction.North);
        building.PlaceBuilding(new Cells(248, 253), Direction.North);
        building.PlaceBuilding(new Cells(246, 253), Direction.North);
        building.PlaceBuilding(new Cells(260, 250), Direction.South);
        building.PlaceBuilding(new Cells(258, 250), Direction.South);
        building.PlaceBuilding(new Cells(256, 250), Direction.South);
        building.PlaceBuilding(new Cells(254, 250), Direction.South);
        building.PlaceBuilding(new Cells(252, 250), Direction.South);
        building.PlaceBuilding(new Cells(250, 250), Direction.South);
        building.PlaceBuilding(new Cells(248, 250), Direction.South);
        building.PlaceBuilding(new Cells(246, 250), Direction.South);
        building.PlaceBuilding(new Cells(243, 256), Direction.West);
        building.PlaceBuilding(new Cells(243, 254), Direction.West);
        building.PlaceBuilding(new Cells(243, 252), Direction.West);
        building.PlaceBuilding(new Cells(243, 250), Direction.West);
        building.PlaceBuilding(new Cells(243, 248), Direction.West);
        building.ResetObjectToBuild(commercial[0]);
        building.PlaceBuilding(new Cells(252, 255), Direction.South);
        building.PlaceBuilding(new Cells(255, 255), Direction.South);
        building.PlaceBuilding(new Cells(258, 255), Direction.South);
        building.ResetObjectToBuild(commercial[1]);
        building.PlaceBuilding(new Cells(261, 255), Direction.South);
        building.ResetObjectToBuild(house);
        building.PlaceBuilding(new Cells(262, 250), Direction.South);
        building.PlaceBuilding(new Cells(264, 250), Direction.South);
        building.PlaceBuilding(new Cells(266, 250), Direction.South);
        building.PlaceBuilding(new Cells(266, 248), Direction.North);
        building.PlaceBuilding(new Cells(264, 248), Direction.North);
        building.PlaceBuilding(new Cells(262, 248), Direction.North);
        building.PlaceBuilding(new Cells(260, 248), Direction.North);
        building.PlaceBuilding(new Cells(258, 248), Direction.North);
        building.PlaceBuilding(new Cells(256, 248), Direction.North);
        building.PlaceBuilding(new Cells(254, 248), Direction.North);
        building.PlaceBuilding(new Cells(252, 248), Direction.North);
        building.PlaceBuilding(new Cells(250, 248), Direction.North);
        building.PlaceBuilding(new Cells(248, 248), Direction.North);
        building.PlaceBuilding(new Cells(246, 248), Direction.North);
        building.PlaceBuilding(new Cells(243, 246), Direction.West);
        building.PlaceBuilding(new Cells(245, 245), Direction.South);
        building.PlaceBuilding(new Cells(247, 245), Direction.South);
        building.PlaceBuilding(new Cells(250, 245), Direction.South);
        building.PlaceBuilding(new Cells(252, 245), Direction.South);
        building.PlaceBuilding(new Cells(254, 245), Direction.South);
        building.PlaceBuilding(new Cells(256, 245), Direction.South);
        building.PlaceBuilding(new Cells(258, 245), Direction.South);
        building.PlaceBuilding(new Cells(260, 245), Direction.South);
        building.PlaceBuilding(new Cells(262, 245), Direction.South);
        building.PlaceBuilding(new Cells(264, 245), Direction.South);
        building.PlaceBuilding(new Cells(266, 245), Direction.South);
        building.PlaceBuilding(new Cells(268, 245), Direction.South);
        building.PlaceBuilding(new Cells(270, 246), Direction.East);
        building.PlaceBuilding(new Cells(262, 253), Direction.North);
        building.PlaceBuilding(new Cells(264, 253), Direction.North);
        building.PlaceBuilding(new Cells(266, 253), Direction.North);
        building.ResetObjectToBuild(commercial[0]);
        building.PlaceBuilding(new Cells(247, 241), Direction.West);
        building.PlaceBuilding(new Cells(247, 238), Direction.West);
        building.PlaceBuilding(new Cells(250, 241), Direction.East);
        building.PlaceBuilding(new Cells(250, 238), Direction.East);
        building.PlaceBuilding(new Cells(250, 235), Direction.East);
        building.PlaceBuilding(new Cells(247, 235), Direction.West);
        building.PlaceBuilding(new Cells(253, 241), Direction.East);
        building.PlaceBuilding(new Cells(253, 238), Direction.East);
        building.PlaceBuilding(new Cells(253, 235), Direction.East);
        building.PlaceBuilding(new Cells(255, 235), Direction.West);
        building.PlaceBuilding(new Cells(255, 238), Direction.West);
        building.PlaceBuilding(new Cells(255, 241), Direction.West);
        building.ResetObjectToBuild(fireStation);
        building.PlaceBuilding(new Cells(254, 230), Direction.South);
        building.ResetObjectToBuild(house);
        building.PlaceBuilding(new Cells(258, 242), Direction.East);
        building.PlaceBuilding(new Cells(258, 240), Direction.East);
        building.PlaceBuilding(new Cells(258, 238), Direction.East);
        building.PlaceBuilding(new Cells(258, 236), Direction.East);
        building.PlaceBuilding(new Cells(260, 236), Direction.West);
        building.PlaceBuilding(new Cells(260, 238), Direction.West);
        building.PlaceBuilding(new Cells(260, 240), Direction.West);
        building.PlaceBuilding(new Cells(260, 242), Direction.West);
        building.PlaceBuilding(new Cells(263, 242), Direction.East);
        building.PlaceBuilding(new Cells(263, 240), Direction.East);
        building.PlaceBuilding(new Cells(263, 238), Direction.East);
        building.PlaceBuilding(new Cells(263, 236), Direction.East);
        building.PlaceBuilding(new Cells(263, 234), Direction.East);
        building.PlaceBuilding(new Cells(261, 232), Direction.South);
        building.ResetObjectToBuild(police);
        building.PlaceBuilding(new Cells(250, 231), Direction.South);
        building.ResetObjectToBuild(commercial[1]);
        building.PlaceBuilding(new Cells(247, 229), Direction.West);
        building.ResetObjectToBuild(road);
        building.PlaceRoad(false, new Cells(249, 247), Direction.North);
        building.PlaceRoad(true, new Cells(249, 247), Direction.North);
        building.PlaceRoad(true, new Cells(249, 247), Direction.South);
        building.PlaceRoad(false, new Cells(249, 246), Direction.North);
        building.PlaceRoad(true, new Cells(249, 246), Direction.North);
        building.PlaceRoad(true, new Cells(249, 246), Direction.South);
        building.PlaceRoad(false, new Cells(249, 245), Direction.North);
        building.PlaceRoad(true, new Cells(249, 245), Direction.North);
        building.PlaceRoad(true, new Cells(249, 245), Direction.South);
        building.PlaceRoad(false, new Cells(249, 244), Direction.North);
        building.PlaceRoad(true, new Cells(249, 244), Direction.North);
        building.PlaceRoad(true, new Cells(249, 244), Direction.South);
        building.PlaceRoad(false, new Cells(249, 243), Direction.North);
        building.PlaceRoad(true, new Cells(249, 243), Direction.North);
        building.PlaceRoad(true, new Cells(249, 243), Direction.South);
        building.PlaceRoad(false, new Cells(249, 242), Direction.North);
        building.PlaceRoad(true, new Cells(249, 242), Direction.North);
        building.PlaceRoad(true, new Cells(249, 242), Direction.South);
        building.PlaceRoad(false, new Cells(249, 241), Direction.North);
        building.PlaceRoad(true, new Cells(249, 241), Direction.North);
        building.PlaceRoad(true, new Cells(249, 241), Direction.South);
        building.PlaceRoad(false, new Cells(249, 240), Direction.North);
        building.PlaceRoad(true, new Cells(249, 240), Direction.North);
        building.PlaceRoad(true, new Cells(249, 240), Direction.South);
        building.PlaceRoad(false, new Cells(249, 239), Direction.North);
        building.PlaceRoad(true, new Cells(249, 239), Direction.North);
        building.PlaceRoad(true, new Cells(249, 239), Direction.South);
        building.PlaceRoad(false, new Cells(249, 238), Direction.North);
        building.PlaceRoad(true, new Cells(249, 238), Direction.North);
        building.PlaceRoad(true, new Cells(249, 238), Direction.South);
        building.PlaceRoad(false, new Cells(249, 237), Direction.North);
        building.PlaceRoad(true, new Cells(249, 237), Direction.North);
        building.PlaceRoad(true, new Cells(249, 237), Direction.South);
        building.PlaceRoad(false, new Cells(249, 236), Direction.North);
        building.PlaceRoad(true, new Cells(249, 236), Direction.North);
        building.PlaceRoad(true, new Cells(249, 236), Direction.South);
        building.PlaceRoad(false, new Cells(249, 235), Direction.North);
        building.PlaceRoad(true, new Cells(249, 235), Direction.North);
        building.PlaceRoad(true, new Cells(249, 235), Direction.South);
        building.PlaceRoad(false, new Cells(249, 234), Direction.North);
        building.PlaceRoad(true, new Cells(249, 234), Direction.North);
        building.PlaceRoad(true, new Cells(249, 234), Direction.South);
        building.PlaceRoad(false, new Cells(249, 233), Direction.North);
        building.PlaceRoad(true, new Cells(249, 233), Direction.North);
        building.PlaceRoad(true, new Cells(249, 233), Direction.South);
        building.PlaceRoad(false, new Cells(249, 232), Direction.North);
        building.PlaceRoad(true, new Cells(249, 232), Direction.North);
        building.PlaceRoad(true, new Cells(249, 232), Direction.South);
        building.PlaceRoad(false, new Cells(249, 231), Direction.North);
        building.PlaceRoad(true, new Cells(249, 231), Direction.North);
        building.PlaceRoad(true, new Cells(249, 231), Direction.South);
        building.PlaceRoad(false, new Cells(249, 230), Direction.North);
        building.PlaceRoad(true, new Cells(249, 230), Direction.North);
        building.PlaceRoad(true, new Cells(249, 230), Direction.South);
        building.PlaceRoad(false, new Cells(249, 229), Direction.North);
        building.PlaceRoad(true, new Cells(249, 234), Direction.East);
        building.PlaceRoad(true, new Cells(249, 234), Direction.West);
        building.PlaceRoad(false, new Cells(250, 234), Direction.East);
        building.PlaceRoad(true, new Cells(250, 234), Direction.East);
        building.PlaceRoad(true, new Cells(250, 234), Direction.West);
        building.PlaceRoad(false, new Cells(251, 234), Direction.East);
        building.PlaceRoad(true, new Cells(251, 234), Direction.East);
        building.PlaceRoad(true, new Cells(251, 234), Direction.West);
        building.PlaceRoad(false, new Cells(252, 234), Direction.East);
        building.PlaceRoad(true, new Cells(252, 234), Direction.East);
        building.PlaceRoad(true, new Cells(252, 234), Direction.West);
        building.PlaceRoad(false, new Cells(253, 234), Direction.East);
        building.PlaceRoad(true, new Cells(253, 234), Direction.East);
        building.PlaceRoad(true, new Cells(253, 234), Direction.West);
        building.PlaceRoad(false, new Cells(254, 234), Direction.East);
        building.PlaceRoad(true, new Cells(254, 234), Direction.East);
        building.PlaceRoad(true, new Cells(254, 234), Direction.West);
        building.PlaceRoad(false, new Cells(255, 234), Direction.East);
        building.PlaceRoad(true, new Cells(255, 234), Direction.East);
        building.PlaceRoad(true, new Cells(255, 234), Direction.West);
        building.PlaceRoad(false, new Cells(256, 234), Direction.East);
        building.PlaceRoad(true, new Cells(256, 234), Direction.East);
        building.PlaceRoad(true, new Cells(256, 234), Direction.West);
        building.PlaceRoad(false, new Cells(257, 234), Direction.East);
        building.PlaceRoad(true, new Cells(257, 234), Direction.East);
        building.PlaceRoad(true, new Cells(257, 234), Direction.West);
        building.PlaceRoad(false, new Cells(258, 234), Direction.East);
        building.PlaceRoad(true, new Cells(258, 234), Direction.East);
        building.PlaceRoad(true, new Cells(258, 234), Direction.West);
        building.PlaceRoad(false, new Cells(259, 234), Direction.East);
        building.PlaceRoad(true, new Cells(259, 234), Direction.East);
        building.PlaceRoad(true, new Cells(259, 234), Direction.West);
        building.PlaceRoad(false, new Cells(260, 234), Direction.East);
        building.PlaceRoad(true, new Cells(260, 234), Direction.East);
        building.PlaceRoad(true, new Cells(260, 234), Direction.West);
        building.PlaceRoad(false, new Cells(261, 234), Direction.East);
        building.PlaceRoad(true, new Cells(261, 234), Direction.East);
        building.PlaceRoad(true, new Cells(261, 234), Direction.West);
        building.PlaceRoad(false, new Cells(262, 234), Direction.East);
        building.PlaceRoad(true, new Cells(262, 234), Direction.South);
        building.PlaceRoad(true, new Cells(262, 234), Direction.South);
        building.PlaceRoad(false, new Cells(262, 235), Direction.South);
        building.PlaceRoad(true, new Cells(262, 235), Direction.South);
        building.PlaceRoad(true, new Cells(262, 235), Direction.South);
        building.PlaceRoad(false, new Cells(262, 236), Direction.South);
        building.PlaceRoad(true, new Cells(262, 236), Direction.South);
        building.PlaceRoad(true, new Cells(262, 236), Direction.South);
        building.PlaceRoad(false, new Cells(262, 237), Direction.South);
        building.PlaceRoad(true, new Cells(262, 237), Direction.South);
        building.PlaceRoad(true, new Cells(262, 237), Direction.South);
        building.PlaceRoad(false, new Cells(262, 238), Direction.South);
        building.PlaceRoad(true, new Cells(262, 238), Direction.South);
        building.PlaceRoad(true, new Cells(262, 238), Direction.South);
        building.PlaceRoad(false, new Cells(262, 239), Direction.South);
        building.PlaceRoad(true, new Cells(262, 239), Direction.South);
        building.PlaceRoad(true, new Cells(262, 239), Direction.South);
        building.PlaceRoad(false, new Cells(262, 240), Direction.South);
        building.PlaceRoad(true, new Cells(262, 240), Direction.South);
        building.PlaceRoad(true, new Cells(262, 240), Direction.South);
        building.PlaceRoad(false, new Cells(262, 241), Direction.South);
        building.PlaceRoad(true, new Cells(262, 241), Direction.South);
        building.PlaceRoad(true, new Cells(262, 241), Direction.South);
        building.PlaceRoad(false, new Cells(262, 242), Direction.South);
        building.PlaceRoad(false, new Cells(262, 243), Direction.South);
        building.PlaceRoad(true, new Cells(257, 234), Direction.South);
        building.PlaceRoad(true, new Cells(257, 234), Direction.South);
        building.PlaceRoad(false, new Cells(257, 235), Direction.South);
        building.PlaceRoad(true, new Cells(257, 235), Direction.South);
        building.PlaceRoad(true, new Cells(257, 235), Direction.South);
        building.PlaceRoad(false, new Cells(257, 236), Direction.South);
        building.PlaceRoad(true, new Cells(257, 236), Direction.South);
        building.PlaceRoad(true, new Cells(257, 236), Direction.South);
        building.PlaceRoad(false, new Cells(257, 237), Direction.South);
        building.PlaceRoad(true, new Cells(257, 237), Direction.South);
        building.PlaceRoad(true, new Cells(257, 237), Direction.South);
        building.PlaceRoad(false, new Cells(257, 238), Direction.South);
        building.PlaceRoad(true, new Cells(257, 238), Direction.South);
        building.PlaceRoad(true, new Cells(257, 238), Direction.South);
        building.PlaceRoad(false, new Cells(257, 239), Direction.South);
        building.PlaceRoad(true, new Cells(257, 239), Direction.South);
        building.PlaceRoad(true, new Cells(257, 239), Direction.South);
        building.PlaceRoad(false, new Cells(257, 240), Direction.South);
        building.PlaceRoad(true, new Cells(257, 240), Direction.South);
        building.PlaceRoad(true, new Cells(257, 240), Direction.South);
        building.PlaceRoad(false, new Cells(257, 241), Direction.South);
        building.PlaceRoad(true, new Cells(257, 241), Direction.South);
        building.PlaceRoad(true, new Cells(257, 241), Direction.South);
        building.PlaceRoad(false, new Cells(257, 242), Direction.South);
        building.PlaceRoad(false, new Cells(257, 243), Direction.South);
        building.PlaceRoad(true, new Cells(252, 234), Direction.South);
        building.PlaceRoad(true, new Cells(252, 234), Direction.South);
        building.PlaceRoad(false, new Cells(252, 235), Direction.South);
        building.PlaceRoad(true, new Cells(252, 235), Direction.South);
        building.PlaceRoad(true, new Cells(252, 235), Direction.South);
        building.PlaceRoad(false, new Cells(252, 236), Direction.South);
        building.PlaceRoad(true, new Cells(252, 236), Direction.South);
        building.PlaceRoad(true, new Cells(252, 236), Direction.South);
        building.PlaceRoad(false, new Cells(252, 237), Direction.South);
        building.PlaceRoad(true, new Cells(252, 237), Direction.South);
        building.PlaceRoad(true, new Cells(252, 237), Direction.South);
        building.PlaceRoad(false, new Cells(252, 238), Direction.South);
        building.PlaceRoad(true, new Cells(252, 238), Direction.South);
        building.PlaceRoad(true, new Cells(252, 238), Direction.South);
        building.PlaceRoad(false, new Cells(252, 239), Direction.South);
        building.PlaceRoad(true, new Cells(252, 239), Direction.South);
        building.PlaceRoad(true, new Cells(252, 239), Direction.South);
        building.PlaceRoad(false, new Cells(252, 240), Direction.South);
        building.PlaceRoad(true, new Cells(252, 240), Direction.South);
        building.PlaceRoad(true, new Cells(252, 240), Direction.South);
        building.PlaceRoad(false, new Cells(252, 241), Direction.South);
        building.PlaceRoad(true, new Cells(252, 241), Direction.South);
        building.PlaceRoad(true, new Cells(252, 241), Direction.South);
        building.PlaceRoad(false, new Cells(252, 242), Direction.South);
        building.PlaceRoad(false, new Cells(252, 243), Direction.South);
        building.PlaceRoad(false, new Cells(264, 244), Direction.North);
        building.PlaceRoad(true, new Cells(264, 244), Direction.West);
        building.PlaceRoad(true, new Cells(264, 244), Direction.East);
        building.PlaceRoad(false, new Cells(263, 244), Direction.West);
        building.PlaceRoad(true, new Cells(263, 244), Direction.West);
        building.PlaceRoad(true, new Cells(263, 244), Direction.West);
        building.PlaceRoad(false, new Cells(262, 244), Direction.West);
        building.PlaceRoad(true, new Cells(262, 244), Direction.West);
        building.PlaceRoad(true, new Cells(262, 244), Direction.West);
        building.PlaceRoad(false, new Cells(261, 244), Direction.West);
        building.PlaceRoad(true, new Cells(261, 244), Direction.West);
        building.PlaceRoad(true, new Cells(261, 244), Direction.West);
        building.PlaceRoad(false, new Cells(260, 244), Direction.West);
        building.PlaceRoad(true, new Cells(260, 244), Direction.West);
        building.PlaceRoad(true, new Cells(260, 244), Direction.West);
        building.PlaceRoad(false, new Cells(259, 244), Direction.West);
        building.PlaceRoad(true, new Cells(259, 244), Direction.West);
        building.PlaceRoad(true, new Cells(259, 244), Direction.West);
        building.PlaceRoad(false, new Cells(258, 244), Direction.West);
        building.PlaceRoad(true, new Cells(258, 244), Direction.West);
        building.PlaceRoad(true, new Cells(258, 244), Direction.West);
        building.PlaceRoad(false, new Cells(257, 244), Direction.West);
        building.PlaceRoad(true, new Cells(257, 244), Direction.West);
        building.PlaceRoad(true, new Cells(257, 244), Direction.West);
        building.PlaceRoad(false, new Cells(256, 244), Direction.West);
        building.PlaceRoad(true, new Cells(256, 244), Direction.West);
        building.PlaceRoad(true, new Cells(256, 244), Direction.West);
        building.PlaceRoad(false, new Cells(255, 244), Direction.West);
        building.PlaceRoad(true, new Cells(255, 244), Direction.West);
        building.PlaceRoad(true, new Cells(255, 244), Direction.West);
        building.PlaceRoad(false, new Cells(254, 244), Direction.West);
        building.PlaceRoad(true, new Cells(254, 244), Direction.West);
        building.PlaceRoad(true, new Cells(254, 244), Direction.West);
        building.PlaceRoad(false, new Cells(253, 244), Direction.West);
        building.PlaceRoad(true, new Cells(253, 244), Direction.West);
        building.PlaceRoad(true, new Cells(253, 244), Direction.West);
        building.PlaceRoad(false, new Cells(252, 244), Direction.West);
        building.PlaceRoad(true, new Cells(252, 244), Direction.West);
        building.PlaceRoad(true, new Cells(252, 244), Direction.West);
        building.PlaceRoad(false, new Cells(251, 244), Direction.West);
        building.PlaceRoad(true, new Cells(249, 244), Direction.East);
        building.PlaceRoad(true, new Cells(251, 244), Direction.West);
        building.PlaceRoad(true, new Cells(249, 244), Direction.West);
        building.PlaceRoad(true, new Cells(251, 244), Direction.West);
        building.PlaceRoad(false, new Cells(250, 244), Direction.West);
        building.PlaceRoad(true, new Cells(249, 244), Direction.North);
        building.PlaceRoad(true, new Cells(249, 244), Direction.North);
        building.PlaceRoad(false, new Cells(248, 244), Direction.West);
        building.PlaceRoad(true, new Cells(248, 244), Direction.West);
        building.PlaceRoad(true, new Cells(248, 244), Direction.West);
        building.PlaceRoad(false, new Cells(247, 244), Direction.West);
        building.PlaceRoad(true, new Cells(247, 244), Direction.West);
        building.PlaceRoad(true, new Cells(247, 244), Direction.West);
        building.PlaceRoad(false, new Cells(246, 244), Direction.West);
        building.PlaceRoad(false, new Cells(269, 247), Direction.North);
        building.PlaceRoad(true, new Cells(269, 247), Direction.West);
        building.PlaceRoad(true, new Cells(269, 247), Direction.East);
        building.PlaceRoad(false, new Cells(268, 247), Direction.West);
        building.PlaceRoad(true, new Cells(268, 247), Direction.West);
        building.PlaceRoad(true, new Cells(268, 247), Direction.West);
        building.PlaceRoad(false, new Cells(267, 247), Direction.West);
        building.PlaceRoad(true, new Cells(267, 247), Direction.West);
        building.PlaceRoad(true, new Cells(267, 247), Direction.West);
        building.PlaceRoad(false, new Cells(266, 247), Direction.West);
        building.PlaceRoad(true, new Cells(266, 247), Direction.West);
        building.PlaceRoad(true, new Cells(266, 247), Direction.West);
        building.PlaceRoad(false, new Cells(265, 247), Direction.West);
        building.PlaceRoad(true, new Cells(265, 247), Direction.West);
        building.PlaceRoad(true, new Cells(265, 247), Direction.West);
        building.PlaceRoad(false, new Cells(264, 247), Direction.West);
        building.PlaceRoad(true, new Cells(264, 247), Direction.West);
        building.PlaceRoad(true, new Cells(264, 247), Direction.West);
        building.PlaceRoad(false, new Cells(263, 247), Direction.West);
        building.PlaceRoad(true, new Cells(263, 247), Direction.West);
        building.PlaceRoad(true, new Cells(263, 247), Direction.West);
        building.PlaceRoad(false, new Cells(262, 247), Direction.West);
        building.PlaceRoad(true, new Cells(262, 247), Direction.West);
        building.PlaceRoad(true, new Cells(262, 247), Direction.West);
        building.PlaceRoad(false, new Cells(261, 247), Direction.West);
        building.PlaceRoad(true, new Cells(261, 247), Direction.West);
        building.PlaceRoad(true, new Cells(261, 247), Direction.West);
        building.PlaceRoad(false, new Cells(260, 247), Direction.West);
        building.PlaceRoad(true, new Cells(260, 247), Direction.West);
        building.PlaceRoad(true, new Cells(260, 247), Direction.West);
        building.PlaceRoad(false, new Cells(259, 247), Direction.West);
        building.PlaceRoad(true, new Cells(259, 247), Direction.West);
        building.PlaceRoad(true, new Cells(259, 247), Direction.West);
        building.PlaceRoad(false, new Cells(258, 247), Direction.West);
        building.PlaceRoad(true, new Cells(258, 247), Direction.West);
        building.PlaceRoad(true, new Cells(258, 247), Direction.West);
        building.PlaceRoad(false, new Cells(257, 247), Direction.West);
        building.PlaceRoad(true, new Cells(257, 247), Direction.West);
        building.PlaceRoad(true, new Cells(257, 247), Direction.West);
        building.PlaceRoad(false, new Cells(256, 247), Direction.West);
        building.PlaceRoad(true, new Cells(256, 247), Direction.West);
        building.PlaceRoad(true, new Cells(256, 247), Direction.West);
        building.PlaceRoad(false, new Cells(255, 247), Direction.West);
        building.PlaceRoad(true, new Cells(255, 247), Direction.West);
        building.PlaceRoad(true, new Cells(255, 247), Direction.West);
        building.PlaceRoad(false, new Cells(254, 247), Direction.West);
        building.PlaceRoad(true, new Cells(254, 247), Direction.West);
        building.PlaceRoad(true, new Cells(254, 247), Direction.West);
        building.PlaceRoad(false, new Cells(253, 247), Direction.West);
        building.PlaceRoad(true, new Cells(253, 247), Direction.West);
        building.PlaceRoad(true, new Cells(253, 247), Direction.West);
        building.PlaceRoad(false, new Cells(252, 247), Direction.West);
        building.PlaceRoad(true, new Cells(252, 247), Direction.West);
        building.PlaceRoad(true, new Cells(252, 247), Direction.West);
        building.PlaceRoad(false, new Cells(251, 247), Direction.West);
        building.PlaceRoad(true, new Cells(249, 247), Direction.South);
        building.PlaceRoad(true, new Cells(251, 247), Direction.West);
        building.PlaceRoad(true, new Cells(249, 247), Direction.North);
        building.PlaceRoad(true, new Cells(251, 247), Direction.West);
        building.PlaceRoad(false, new Cells(250, 247), Direction.West);
        building.PlaceRoad(true, new Cells(249, 247), Direction.West);
        building.PlaceRoad(true, new Cells(249, 247), Direction.North);
        building.PlaceRoad(false, new Cells(248, 247), Direction.West);
        building.PlaceRoad(true, new Cells(248, 247), Direction.West);
        building.PlaceRoad(true, new Cells(248, 247), Direction.West);
        building.PlaceRoad(false, new Cells(247, 247), Direction.West);
        building.PlaceRoad(true, new Cells(247, 247), Direction.West);
        building.PlaceRoad(true, new Cells(247, 247), Direction.West);
        building.PlaceRoad(false, new Cells(246, 247), Direction.West);
        building.PlaceRoad(true, new Cells(246, 247), Direction.West);
        building.PlaceRoad(true, new Cells(246, 247), Direction.West);
        building.PlaceRoad(false, new Cells(245, 247), Direction.West);
        building.PlaceRoad(false, new Cells(245, 257), Direction.North);
        building.PlaceRoad(true, new Cells(245, 257), Direction.North);
        building.PlaceRoad(true, new Cells(245, 257), Direction.South);
        building.PlaceRoad(false, new Cells(245, 256), Direction.North);
        building.PlaceRoad(true, new Cells(245, 256), Direction.North);
        building.PlaceRoad(true, new Cells(245, 256), Direction.South);
        building.PlaceRoad(false, new Cells(245, 255), Direction.North);
        building.PlaceRoad(true, new Cells(245, 255), Direction.North);
        building.PlaceRoad(true, new Cells(245, 255), Direction.South);
        building.PlaceRoad(false, new Cells(245, 254), Direction.North);
        building.PlaceRoad(true, new Cells(245, 254), Direction.North);
        building.PlaceRoad(true, new Cells(245, 254), Direction.South);
        building.PlaceRoad(false, new Cells(245, 253), Direction.North);
        building.PlaceRoad(true, new Cells(245, 253), Direction.North);
        building.PlaceRoad(true, new Cells(245, 253), Direction.South);
        building.PlaceRoad(false, new Cells(245, 252), Direction.North);
        building.PlaceRoad(true, new Cells(245, 252), Direction.North);
        building.PlaceRoad(true, new Cells(245, 252), Direction.South);
        building.PlaceRoad(false, new Cells(245, 251), Direction.North);
        building.PlaceRoad(true, new Cells(245, 251), Direction.North);
        building.PlaceRoad(true, new Cells(245, 251), Direction.South);
        building.PlaceRoad(false, new Cells(245, 250), Direction.North);
        building.PlaceRoad(true, new Cells(245, 250), Direction.North);
        building.PlaceRoad(true, new Cells(245, 250), Direction.South);
        building.PlaceRoad(false, new Cells(245, 249), Direction.North);
        building.PlaceRoad(true, new Cells(245, 247), Direction.West);
        building.PlaceRoad(true, new Cells(245, 249), Direction.North);
        building.PlaceRoad(true, new Cells(245, 247), Direction.West);
        building.PlaceRoad(true, new Cells(245, 249), Direction.South);
        building.PlaceRoad(false, new Cells(245, 248), Direction.South);
        building.PlaceRoad(false, new Cells(247, 257), Direction.North);
        building.PlaceRoad(true, new Cells(247, 257), Direction.East);
        building.PlaceRoad(true, new Cells(247, 257), Direction.West);
        building.PlaceRoad(false, new Cells(248, 257), Direction.East);
        building.PlaceRoad(true, new Cells(245, 257), Direction.South);
        building.PlaceRoad(true, new Cells(247, 257), Direction.West);
        building.PlaceRoad(true, new Cells(245, 257), Direction.North);
        building.PlaceRoad(true, new Cells(247, 257), Direction.West);
        building.PlaceRoad(false, new Cells(246, 257), Direction.West);
        building.PlaceRoad(true, new Cells(248, 257), Direction.East);
        building.PlaceRoad(true, new Cells(248, 257), Direction.West);
        building.PlaceRoad(false, new Cells(249, 257), Direction.East);
        building.PlaceRoad(true, new Cells(249, 257), Direction.East);
        building.PlaceRoad(true, new Cells(249, 257), Direction.West);
        building.PlaceRoad(false, new Cells(250, 257), Direction.East);
        building.PlaceRoad(true, new Cells(250, 257), Direction.East);
        building.PlaceRoad(true, new Cells(250, 257), Direction.West);
        building.PlaceRoad(false, new Cells(251, 257), Direction.East);
        building.PlaceRoad(true, new Cells(251, 257), Direction.East);
        building.PlaceRoad(true, new Cells(251, 257), Direction.West);
        building.PlaceRoad(false, new Cells(252, 257), Direction.East);
        building.PlaceRoad(true, new Cells(252, 257), Direction.East);
        building.PlaceRoad(true, new Cells(252, 257), Direction.West);
        building.PlaceRoad(false, new Cells(253, 257), Direction.East);
        building.PlaceRoad(true, new Cells(253, 257), Direction.East);
        building.PlaceRoad(true, new Cells(253, 257), Direction.West);
        building.PlaceRoad(false, new Cells(254, 257), Direction.East);
        building.PlaceRoad(true, new Cells(254, 257), Direction.East);
        building.PlaceRoad(true, new Cells(254, 257), Direction.West);
        building.PlaceRoad(false, new Cells(255, 257), Direction.East);
        building.PlaceRoad(true, new Cells(255, 257), Direction.East);
        building.PlaceRoad(true, new Cells(255, 257), Direction.West);
        building.PlaceRoad(false, new Cells(256, 257), Direction.East);
        building.PlaceRoad(true, new Cells(256, 257), Direction.East);
        building.PlaceRoad(true, new Cells(256, 257), Direction.West);
        building.PlaceRoad(false, new Cells(257, 257), Direction.East);
        building.PlaceRoad(true, new Cells(257, 257), Direction.East);
        building.PlaceRoad(true, new Cells(257, 257), Direction.West);
        building.PlaceRoad(false, new Cells(258, 257), Direction.East);
        building.PlaceRoad(true, new Cells(258, 257), Direction.East);
        building.PlaceRoad(true, new Cells(258, 257), Direction.West);
        building.PlaceRoad(false, new Cells(259, 257), Direction.East);
        building.PlaceRoad(true, new Cells(259, 257), Direction.East);
        building.PlaceRoad(true, new Cells(259, 257), Direction.West);
        building.PlaceRoad(false, new Cells(260, 257), Direction.East);
        building.PlaceRoad(true, new Cells(260, 257), Direction.East);
        building.PlaceRoad(true, new Cells(260, 257), Direction.West);
        building.PlaceRoad(false, new Cells(261, 257), Direction.East);
        building.PlaceRoad(true, new Cells(261, 257), Direction.East);
        building.PlaceRoad(true, new Cells(261, 257), Direction.West);
        building.PlaceRoad(false, new Cells(262, 257), Direction.East);
        building.PlaceRoad(true, new Cells(262, 257), Direction.East);
        building.PlaceRoad(true, new Cells(262, 257), Direction.West);
        building.PlaceRoad(false, new Cells(263, 257), Direction.East);
        building.PlaceRoad(true, new Cells(263, 257), Direction.East);
        building.PlaceRoad(true, new Cells(263, 257), Direction.West);
        building.PlaceRoad(false, new Cells(264, 257), Direction.East);
        building.PlaceRoad(true, new Cells(264, 257), Direction.East);
        building.PlaceRoad(true, new Cells(264, 257), Direction.West);
        building.PlaceRoad(false, new Cells(265, 257), Direction.East);
        building.PlaceRoad(true, new Cells(265, 257), Direction.East);
        building.PlaceRoad(true, new Cells(265, 257), Direction.West);
        building.PlaceRoad(false, new Cells(266, 257), Direction.East);
        building.PlaceRoad(true, new Cells(266, 257), Direction.East);
        building.PlaceRoad(true, new Cells(266, 257), Direction.West);
        building.PlaceRoad(false, new Cells(267, 257), Direction.East);
        building.PlaceRoad(true, new Cells(245, 252), Direction.East);
        building.PlaceRoad(true, new Cells(245, 252), Direction.West);
        building.PlaceRoad(false, new Cells(246, 252), Direction.East);
        building.PlaceRoad(true, new Cells(246, 252), Direction.East);
        building.PlaceRoad(true, new Cells(246, 252), Direction.West);
        building.PlaceRoad(false, new Cells(247, 252), Direction.East);
        building.PlaceRoad(true, new Cells(247, 252), Direction.East);
        building.PlaceRoad(true, new Cells(247, 252), Direction.West);
        building.PlaceRoad(false, new Cells(248, 252), Direction.East);
        building.PlaceRoad(true, new Cells(248, 252), Direction.East);
        building.PlaceRoad(true, new Cells(248, 252), Direction.West);
        building.PlaceRoad(false, new Cells(249, 252), Direction.East);
        building.PlaceRoad(true, new Cells(249, 252), Direction.East);
        building.PlaceRoad(true, new Cells(249, 252), Direction.West);
        building.PlaceRoad(false, new Cells(250, 252), Direction.East);
        building.PlaceRoad(true, new Cells(250, 252), Direction.East);
        building.PlaceRoad(true, new Cells(250, 252), Direction.West);
        building.PlaceRoad(false, new Cells(251, 252), Direction.East);
        building.PlaceRoad(true, new Cells(251, 252), Direction.East);
        building.PlaceRoad(true, new Cells(251, 252), Direction.West);
        building.PlaceRoad(false, new Cells(252, 252), Direction.East);
        building.PlaceRoad(true, new Cells(252, 252), Direction.East);
        building.PlaceRoad(true, new Cells(252, 252), Direction.West);
        building.PlaceRoad(false, new Cells(253, 252), Direction.East);
        building.PlaceRoad(true, new Cells(253, 252), Direction.East);
        building.PlaceRoad(true, new Cells(253, 252), Direction.West);
        building.PlaceRoad(false, new Cells(254, 252), Direction.East);
        building.PlaceRoad(true, new Cells(254, 252), Direction.East);
        building.PlaceRoad(true, new Cells(254, 252), Direction.West);
        building.PlaceRoad(false, new Cells(255, 252), Direction.East);
        building.PlaceRoad(true, new Cells(255, 252), Direction.East);
        building.PlaceRoad(true, new Cells(255, 252), Direction.West);
        building.PlaceRoad(false, new Cells(256, 252), Direction.East);
        building.PlaceRoad(true, new Cells(256, 252), Direction.East);
        building.PlaceRoad(true, new Cells(256, 252), Direction.West);
        building.PlaceRoad(false, new Cells(257, 252), Direction.East);
        building.PlaceRoad(true, new Cells(257, 252), Direction.East);
        building.PlaceRoad(true, new Cells(257, 252), Direction.West);
        building.PlaceRoad(false, new Cells(258, 252), Direction.East);
        building.PlaceRoad(true, new Cells(258, 252), Direction.East);
        building.PlaceRoad(true, new Cells(258, 252), Direction.West);
        building.PlaceRoad(false, new Cells(259, 252), Direction.East);
        building.PlaceRoad(true, new Cells(259, 252), Direction.East);
        building.PlaceRoad(true, new Cells(259, 252), Direction.West);
        building.PlaceRoad(false, new Cells(260, 252), Direction.East);
        building.PlaceRoad(true, new Cells(260, 252), Direction.East);
        building.PlaceRoad(true, new Cells(260, 252), Direction.West);
        building.PlaceRoad(false, new Cells(261, 252), Direction.East);
        building.PlaceRoad(true, new Cells(261, 252), Direction.East);
        building.PlaceRoad(true, new Cells(261, 252), Direction.West);
        building.PlaceRoad(false, new Cells(262, 252), Direction.East);
        building.PlaceRoad(true, new Cells(262, 252), Direction.East);
        building.PlaceRoad(true, new Cells(262, 252), Direction.West);
        building.PlaceRoad(false, new Cells(263, 252), Direction.East);
        building.PlaceRoad(true, new Cells(263, 252), Direction.East);
        building.PlaceRoad(true, new Cells(263, 252), Direction.West);
        building.PlaceRoad(false, new Cells(264, 252), Direction.East);
        building.PlaceRoad(true, new Cells(264, 252), Direction.East);
        building.PlaceRoad(true, new Cells(264, 252), Direction.West);
        building.PlaceRoad(false, new Cells(265, 252), Direction.East);
        building.PlaceRoad(true, new Cells(265, 252), Direction.East);
        building.PlaceRoad(true, new Cells(265, 252), Direction.West);
        building.PlaceRoad(false, new Cells(266, 252), Direction.East);
        building.PlaceRoad(true, new Cells(266, 252), Direction.East);
        building.PlaceRoad(true, new Cells(266, 252), Direction.West);
        building.PlaceRoad(false, new Cells(267, 252), Direction.East);
        building.PlaceRoad(true, new Cells(267, 252), Direction.East);
        building.PlaceRoad(true, new Cells(267, 252), Direction.West);
        building.PlaceRoad(false, new Cells(268, 252), Direction.East);
        building.PlaceRoad(true, new Cells(269, 247), Direction.South);
        building.PlaceRoad(true, new Cells(269, 247), Direction.South);
        building.PlaceRoad(false, new Cells(269, 248), Direction.South);
        building.PlaceRoad(true, new Cells(269, 248), Direction.South);
        building.PlaceRoad(true, new Cells(269, 248), Direction.South);
        building.PlaceRoad(false, new Cells(269, 249), Direction.South);
        building.PlaceRoad(true, new Cells(269, 249), Direction.South);
        building.PlaceRoad(true, new Cells(269, 249), Direction.South);
        building.PlaceRoad(false, new Cells(269, 250), Direction.South);
        building.PlaceRoad(true, new Cells(269, 250), Direction.South);
        building.PlaceRoad(true, new Cells(269, 250), Direction.South);
        building.PlaceRoad(false, new Cells(269, 251), Direction.South);
        building.PlaceRoad(true, new Cells(268, 252), Direction.East);
        building.PlaceRoad(true, new Cells(269, 251), Direction.South);
        building.PlaceRoad(true, new Cells(268, 252), Direction.West);
        building.PlaceRoad(true, new Cells(269, 251), Direction.South);
        building.PlaceRoad(false, new Cells(269, 252), Direction.East);
        building.PlaceRoad(true, new Cells(269, 252), Direction.North);
        building.PlaceRoad(true, new Cells(269, 252), Direction.East);
        building.PlaceRoad(false, new Cells(269, 253), Direction.South);
        building.PlaceRoad(true, new Cells(269, 253), Direction.South);
        building.PlaceRoad(true, new Cells(269, 253), Direction.South);
        building.PlaceRoad(false, new Cells(269, 254), Direction.South);
        building.PlaceRoad(true, new Cells(269, 254), Direction.South);
        building.PlaceRoad(true, new Cells(269, 254), Direction.South);
        building.PlaceRoad(false, new Cells(269, 255), Direction.South);
        building.PlaceRoad(true, new Cells(267, 257), Direction.East);
        building.PlaceRoad(true, new Cells(267, 257), Direction.West);
        building.PlaceRoad(false, new Cells(268, 257), Direction.East);
        building.PlaceRoad(true, new Cells(268, 257), Direction.East);
        building.PlaceRoad(true, new Cells(268, 257), Direction.West);
        building.PlaceRoad(false, new Cells(269, 257), Direction.East);
        building.PlaceRoad(true, new Cells(269, 255), Direction.South);
        building.PlaceRoad(true, new Cells(269, 257), Direction.West);
        building.PlaceRoad(true, new Cells(269, 255), Direction.South);
        building.PlaceRoad(true, new Cells(269, 257), Direction.East);
        building.PlaceRoad(false, new Cells(269, 256), Direction.South);
    }

    void PlaceRoads(Cells start, Cells end)
    {
        if (start.x < end.x)
            for (int x = start.x; x <= end.x; x++)
                building.PlaceRoad(true, new Cells(x, start.z));
        else if (start.z < end.z)
            for (int z = start.z; z <= end.z; z++)
                building.PlaceRoad(true, new Cells(start.x, z));
        else if (start.x > end.x)
            for (int x = start.x; x >= end.x; x--)
                building.PlaceRoad(true, new Cells(x, start.z));
        else if (start.z > end.z)
            for (int z = start.z; z >= end.z; z--)
                building.PlaceRoad(true, new Cells(start.x, z));
    }

}
